import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import LogoScrib3 from '../components/LogoScrib3';
import BurgerButton from '../components/BurgerButton';
import { useIsMobile } from '../hooks/useIsMobile';

const easing = 'cubic-bezier(0.22, 0.61, 0.36, 1)';

/* ------------------------------------------------------------------ */
/*  Week helpers                                                       */
/* ------------------------------------------------------------------ */

function getMonday(d: Date): Date {
  const date = new Date(d);
  const day = date.getDay();
  const diff = date.getDate() - day + (day === 0 ? -6 : 1);
  date.setDate(diff);
  date.setHours(0, 0, 0, 0);
  return date;
}

function addDays(d: Date, n: number): Date {
  const r = new Date(d);
  r.setDate(r.getDate() + n);
  return r;
}

function fmtShort(d: Date): string {
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short' });
}

/* ------------------------------------------------------------------ */
/*  Mock data                                                          */
/* ------------------------------------------------------------------ */

const mockSlack = { count: 47 };
const mockLinear = { completed: 12, inProgress: 3 };
const mockTodos = { completed: 8, pending: 5 };

const mockEisenhower: Record<string, { label: string; items: string[] }> = {
  ui: { label: 'Urgent + Important', items: ['Cardano blog post revision (overdue)', 'Franklin Templeton Q1 report sign-off', 'Invoice dispute — Vendor #3'] },
  i:  { label: 'Important', items: ['SOW renewal — Rootstock', 'Hiring brief: Senior Editor', 'Culture book update'] },
  u:  { label: 'Urgent', items: ['Slack reply — CK re: design assets', 'Linear bug triage (3 P1s)'] },
  n:  { label: 'Neither', items: ['Tool directory cleanup', 'Update team bios page'] },
};

const mockWeekendMessages = [
  { client: 'Cardano', detail: '2 untagged messages' },
  { client: 'Franklin Templeton', detail: '1 untagged thread' },
];

const mockPreview = `**Monday Message — Week of {{WEEK}}**

---

### Data Sources
- **Slack**: 47 messages across 12 channels
- **Linear**: 12 issues completed, 3 in progress
- **To-Do Lists**: 8 completed, 5 pending carry-over

### Priority Matrix
**Urgent + Important**
- Cardano blog post revision (overdue)
- Franklin Templeton Q1 report sign-off
- Invoice dispute — Vendor #3

**Important (not urgent)**
- SOW renewal — Rootstock
- Hiring brief: Senior Editor

### Weekend Client Activity
- **Cardano** — 2 untagged messages (Sat 14:22, Sun 09:05)
- **Franklin Templeton** — 1 untagged thread (Sun 11:30)

### Recommended Actions
1. Reply to Cardano thread before 9am
2. Escalate invoice dispute to Camila
3. Schedule SOW call with Rootstock by Wednesday

---
*Auto-generated by SCRIB3-OS Monday Message. Review before distribution.*`;

/* ------------------------------------------------------------------ */
/*  Shared small components                                            */
/* ------------------------------------------------------------------ */

const Stat: React.FC<{ value: string; label: string; accent?: boolean }> = ({ value, label, accent }) => (
  <div className="flex flex-col gap-1">
    <span style={{ fontFamily: "'Kaio', sans-serif", fontWeight: 800, fontSize: '24px', color: accent ? '#E74C3C' : 'var(--text-primary)' }}>{value}</span>
    <span style={{ fontFamily: "'Owners Wide', sans-serif", fontSize: '11px', letterSpacing: '1px', textTransform: 'uppercase', opacity: 0.45 }}>{label}</span>
  </div>
);

const SectionTitle: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <h3 style={{ fontFamily: "'Kaio', sans-serif", fontWeight: 800, fontSize: '16px', textTransform: 'uppercase', fontFeatureSettings: "'ordn' 1, 'dlig' 1", margin: '0 0 12px 0' }}>
    {children}
  </h3>
);

/* ------------------------------------------------------------------ */
/*  1. Week Selector                                                   */
/* ------------------------------------------------------------------ */

const WeekSelector: React.FC<{ weekStart: Date; onChange: (d: Date) => void }> = ({ weekStart, onChange }) => {
  const weekEnd = addDays(weekStart, 6);
  const btnStyle: React.CSSProperties = {
    fontFamily: "'Kaio', sans-serif", fontWeight: 800, fontSize: '18px',
    background: 'none', border: '1px solid var(--border-default)', borderRadius: '50%',
    width: 36, height: 36, display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
    cursor: 'pointer', color: 'var(--text-primary)', transition: `opacity 0.2s ${easing}`,
  };
  return (
    <div className="flex items-center gap-4" style={{ marginBottom: '32px' }}>
      <button style={btnStyle} onClick={() => onChange(addDays(weekStart, -7))}
        onMouseEnter={(e) => (e.currentTarget.style.opacity = '0.6')} onMouseLeave={(e) => (e.currentTarget.style.opacity = '1')}>
        &lsaquo;
      </button>
      <span style={{ fontFamily: "'Owners Wide', sans-serif", fontSize: '14px', letterSpacing: '0.5px' }}>
        {fmtShort(weekStart)} &mdash; {fmtShort(weekEnd)}
      </span>
      <button style={btnStyle} onClick={() => onChange(addDays(weekStart, 7))}
        onMouseEnter={(e) => (e.currentTarget.style.opacity = '0.6')} onMouseLeave={(e) => (e.currentTarget.style.opacity = '1')}>
        &rsaquo;
      </button>
    </div>
  );
};

/* ------------------------------------------------------------------ */
/*  2. Data Sources                                                    */
/* ------------------------------------------------------------------ */

interface SourceCardProps { title: string; detail: string; enabled: boolean; onToggle: () => void }

const SourceCard: React.FC<SourceCardProps> = ({ title, detail, enabled, onToggle }) => (
  <div style={{
    flex: '1 1 220px', minWidth: 220,
    border: '0.733px solid var(--border-default)', borderRadius: '10.258px',
    padding: '20px 24px', opacity: enabled ? 1 : 0.4,
    transition: `opacity 0.2s ${easing}`,
  }}>
    <div className="flex items-center justify-between" style={{ marginBottom: '12px' }}>
      <span style={{ fontFamily: "'Kaio', sans-serif", fontWeight: 800, fontSize: '13px', textTransform: 'uppercase' }}>{title}</span>
      <button onClick={onToggle} style={{
        width: 40, height: 22, borderRadius: 11, border: 'none', cursor: 'pointer', position: 'relative' as const,
        background: enabled ? '#D7ABC5' : 'rgba(0,0,0,0.12)', transition: `background 0.2s ${easing}`,
      }}>
        <span style={{
          position: 'absolute' as const, top: 2, left: enabled ? 20 : 2,
          width: 18, height: 18, borderRadius: '50%', background: '#fff',
          transition: `left 0.2s ${easing}`, boxShadow: '0 1px 3px rgba(0,0,0,0.15)',
        }} />
      </button>
    </div>
    <span style={{ fontFamily: "'Owners Wide', sans-serif", fontSize: '12px', opacity: 0.6 }}>{detail}</span>
  </div>
);

const DataSources: React.FC = () => {
  const [sources, setSources] = useState({ slack: true, linear: true, todos: true });
  const toggle = (key: keyof typeof sources) => setSources((p) => ({ ...p, [key]: !p[key] }));

  return (
    <div style={{ marginBottom: '40px' }}>
      <SectionTitle>Data Sources</SectionTitle>
      <div className="flex flex-wrap gap-4">
        <SourceCard title="Slack Messages" detail={`${mockSlack.count} messages`} enabled={sources.slack} onToggle={() => toggle('slack')} />
        <SourceCard title="Linear Issues" detail={`${mockLinear.completed} completed, ${mockLinear.inProgress} in progress`} enabled={sources.linear} onToggle={() => toggle('linear')} />
        <SourceCard title="To-Do Lists" detail={`${mockTodos.completed} completed, ${mockTodos.pending} pending`} enabled={sources.todos} onToggle={() => toggle('todos')} />
      </div>
    </div>
  );
};

/* ------------------------------------------------------------------ */
/*  3. Eisenhower Matrix                                               */
/* ------------------------------------------------------------------ */

const quadrantColors: Record<string, { bg: string; border: string }> = {
  ui: { bg: 'rgba(231,76,60,0.06)', border: 'rgba(231,76,60,0.25)' },
  i:  { bg: 'rgba(110,147,195,0.08)', border: 'rgba(110,147,195,0.25)' },
  u:  { bg: 'rgba(230,126,34,0.08)', border: 'rgba(230,126,34,0.25)' },
  n:  { bg: 'rgba(0,0,0,0.03)', border: 'rgba(0,0,0,0.08)' },
};

const EisenhowerMatrix: React.FC<{ isMobile: boolean }> = ({ isMobile }) => (
  <div style={{ marginBottom: '40px' }}>
    <SectionTitle>Priority Matrix</SectionTitle>
    <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr', gap: '12px' }}>
      {(['ui', 'i', 'u', 'n'] as const).map((key) => {
        const q = mockEisenhower[key];
        const c = quadrantColors[key];
        return (
          <div key={key} style={{ background: c.bg, border: `1px solid ${c.border}`, borderRadius: '10.258px', padding: '20px 24px', minHeight: 120 }}>
            <span style={{ fontFamily: "'Kaio', sans-serif", fontWeight: 800, fontSize: '12px', textTransform: 'uppercase', display: 'block', marginBottom: '12px' }}>
              {q.label}
            </span>
            {q.items.map((item, idx) => (
              <div key={idx} style={{
                fontFamily: "'Owners Wide', sans-serif", fontSize: '12px', lineHeight: 1.6,
                padding: '6px 12px', marginBottom: '6px',
                background: 'rgba(255,255,255,0.6)', borderRadius: '6px',
                border: '1px solid rgba(0,0,0,0.06)', cursor: 'grab',
              }}>
                {item}
              </div>
            ))}
          </div>
        );
      })}
    </div>
  </div>
);

/* ------------------------------------------------------------------ */
/*  4. Client Weekend Scanner                                          */
/* ------------------------------------------------------------------ */

const WeekendScanner: React.FC = () => (
  <div style={{ marginBottom: '40px' }}>
    <SectionTitle>Client Weekend Scanner</SectionTitle>
    <div style={{ background: 'rgba(230,126,34,0.08)', border: '1px solid rgba(230,126,34,0.3)', borderRadius: '10.258px', padding: '20px 24px' }}>
      <span style={{ fontFamily: "'Owners Wide', sans-serif", fontSize: '12px', opacity: 0.6, display: 'block', marginBottom: '12px' }}>
        Untagged client messages from Saturday / Sunday
      </span>
      {mockWeekendMessages.map((msg, idx) => (
        <div key={idx} className="flex items-center gap-3" style={{ padding: '8px 0', borderTop: idx > 0 ? '0.5px solid rgba(0,0,0,0.06)' : 'none' }}>
          <span style={{ fontFamily: "'Kaio', sans-serif", fontWeight: 800, fontSize: '13px', textTransform: 'uppercase', minWidth: 180 }}>
            {msg.client}
          </span>
          <span style={{ fontFamily: "'Owners Wide', sans-serif", fontSize: '12px', opacity: 0.7 }}>
            {msg.detail}
          </span>
        </div>
      ))}
    </div>
  </div>
);

/* ------------------------------------------------------------------ */
/*  5. Delivery Options                                                */
/* ------------------------------------------------------------------ */

const DeliveryOptions: React.FC<{ value: string; onChange: (v: string) => void }> = ({ value, onChange }) => {
  const options = [
    { id: 'sunday-email', label: 'Sunday afternoon email' },
    { id: 'monday-dashboard', label: 'Monday 6am dashboard drop' },
  ];

  return (
    <div style={{ marginBottom: '40px' }}>
      <SectionTitle>Delivery</SectionTitle>
      <div className="flex flex-col gap-3">
        {options.map((opt) => (
          <label key={opt.id} className="flex items-center gap-3" style={{ cursor: 'pointer' }} onClick={() => onChange(opt.id)}>
            <span style={{
              width: 20, height: 20, borderRadius: '50%',
              border: value === opt.id ? '2px solid #D7ABC5' : '2px solid var(--border-default)',
              display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
              transition: `border-color 0.15s ${easing}`,
            }}>
              {value === opt.id && <span style={{ width: 10, height: 10, borderRadius: '50%', background: '#D7ABC5' }} />}
            </span>
            <span style={{ fontFamily: "'Owners Wide', sans-serif", fontSize: '13px' }}>{opt.label}</span>
          </label>
        ))}
      </div>
    </div>
  );
};

/* ------------------------------------------------------------------ */
/*  6. Preview Section                                                 */
/* ------------------------------------------------------------------ */

const PreviewSection: React.FC<{ weekLabel: string }> = ({ weekLabel }) => {
  const rendered = mockPreview.replace('{{WEEK}}', weekLabel);
  return (
    <div style={{ marginBottom: '40px' }}>
      <SectionTitle>Preview</SectionTitle>
      <div style={{ border: '0.733px solid var(--border-default)', borderRadius: '10.258px', padding: '28px', background: 'var(--bg-surface)', maxHeight: 480, overflowY: 'auto' }}>
        <pre style={{
          fontFamily: "'Owners Wide', sans-serif", fontSize: '12px', lineHeight: 1.8,
          whiteSpace: 'pre-wrap', wordBreak: 'break-word', margin: 0, color: 'var(--text-primary)',
        }}>
          {rendered}
        </pre>
      </div>
    </div>
  );
};

/* ------------------------------------------------------------------ */
/*  7. Generate Button                                                 */
/* ------------------------------------------------------------------ */

const GenerateButton: React.FC = () => {
  const [toast, setToast] = useState(false);

  return (
    <div style={{ position: 'relative' as const, marginBottom: '60px' }}>
      <button
        onClick={() => { setToast(true); setTimeout(() => setToast(false), 2500); }}
        style={{
          fontFamily: "'Owners Wide', sans-serif", fontSize: '13px', letterSpacing: '1px', textTransform: 'uppercase',
          background: '#D7ABC5', color: '#000', border: 'none', borderRadius: '75.641px',
          padding: '14px 36px', cursor: 'pointer', transition: `opacity 0.2s ${easing}`,
        }}
        onMouseEnter={(e) => (e.currentTarget.style.opacity = '0.8')}
        onMouseLeave={(e) => (e.currentTarget.style.opacity = '1')}
      >
        Generate Monday Message
      </button>

      {toast && (
        <div style={{
          position: 'fixed' as const, bottom: 32, left: '50%', transform: 'translateX(-50%)',
          background: '#000', color: '#EAF2D7', fontFamily: "'Owners Wide', sans-serif", fontSize: '12px',
          letterSpacing: '0.5px', padding: '12px 24px', borderRadius: '75.641px', zIndex: 999,
          animation: 'fadeIn 0.2s ease',
        }}>
          Integration required — connect Slack, Linear, and To-Do sources to generate.
        </div>
      )}
    </div>
  );
};

/* ------------------------------------------------------------------ */
/*  Page                                                               */
/* ------------------------------------------------------------------ */

const MondayMessagePage: React.FC = () => {
  const navigate = useNavigate();
  const isMobile = useIsMobile();
  const [weekStart, setWeekStart] = useState(() => getMonday(new Date()));
  const [delivery, setDelivery] = useState('monday-dashboard');

  const weekLabel = `${fmtShort(weekStart)} - ${fmtShort(addDays(weekStart, 6))}`;

  return (
    <div className="os-root" style={{ minHeight: '100vh' }}>
      {/* Header */}
      <header className="flex items-center justify-between" style={{
        position: 'fixed' as const, top: 0, left: 0, right: 0, zIndex: 40,
        background: 'var(--bg-primary)', height: '85px',
        padding: isMobile ? '0 16px' : '0 40px',
        borderBottom: '0.733px solid var(--border-default)',
      }}>
        <button onClick={() => navigate('/dashboard')} style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0 }}>
          <LogoScrib3 height={18} color="var(--text-primary)" />
        </button>
        <span style={{ fontFamily: "'Owners Wide', sans-serif", fontSize: '12px', letterSpacing: '1px', textTransform: 'uppercase', opacity: 0.5 }}>
          Monday Message
        </span>
        <BurgerButton />
      </header>

      {/* Content */}
      <div style={{ padding: isMobile ? '16px' : '40px', maxWidth: '1200px', margin: '0 auto' }}>
        <h1 style={{
          fontFamily: "'Kaio', sans-serif", fontWeight: 800,
          fontSize: isMobile ? '24px' : '32px', textTransform: 'uppercase',
          fontFeatureSettings: "'ordn' 1, 'dlig' 1", margin: '0 0 8px 0',
        }}>
          Monday Message
        </h1>
        <p style={{ fontFamily: "'Owners Wide', sans-serif", fontSize: '13px', opacity: 0.5, marginBottom: '24px' }}>
          Weekly aggregator — review your week, prioritise, and ship.
        </p>

        {/* Stats */}
        <div className="flex gap-6 flex-wrap" style={{ marginBottom: '24px' }}>
          <Stat value={mockSlack.count.toString()} label="slack messages" />
          <Stat value={(mockLinear.completed + mockLinear.inProgress).toString()} label="linear issues" />
          <Stat value={(mockTodos.completed + mockTodos.pending).toString()} label="to-do items" />
          <Stat value={mockWeekendMessages.length.toString()} label="weekend flags" accent />
        </div>

        {/* Week selector */}
        <WeekSelector weekStart={weekStart} onChange={setWeekStart} />

        {/* Sections */}
        <DataSources />
        <EisenhowerMatrix isMobile={isMobile} />
        <WeekendScanner />
        <DeliveryOptions value={delivery} onChange={setDelivery} />
        <PreviewSection weekLabel={weekLabel} />
        <GenerateButton />
      </div>
    </div>
  );
};

export default MondayMessagePage;
